site_name: Indigon Docs
site_url: https://indigonbending.github.io/docs/
site_author: Aztl
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: amber
  favicon: icon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expansion
    - toc.integrate
plugins:
    - search
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VYE5WWr
      name: Indigon Discord
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@indigonbending
      name: Indigon on TikTok
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/indigonmc/
      name: Indigon on Instagram
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/indigonmc
      name: Indigon on Twitter
